backend:
  name: git-gateway
  branch: main
  repo: PatrickMcGrath29/thegoodland
  squash_merges: true
  use_graphql: true

site_url: https://thegoodland.io
display_url: https://thegoodland.io

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: collections
    label: Collections
    folder: content/collections
    format: frontmatter
    create: true
    slug: '{{name}}-{{author}}'
    summary: '{{name}}'
    editor:
      preview: false
    fields:
      - {label: Slug Fields, name: slugFields, widget: hidden, default: [name, author]}
      - {label: Collection Name, name: name, widget: string}
      - label: Author
        name: author
        widget: relation
        collection: authors
        search_fields: [name]
        value_field: name
        display_fields: [name]
        required: false
        hint: 'Optional, the author associated with this collection.'
      - label: Summary
        name: summary
        widget: text
        required: true
        hint: 'Optional, a short description of the collection.'
      - label: Posts
        name: posts
        widget: list
        fields:
          - label: Post
            name: post
            widget: relation
            collection: posts
            search_fields: [title]
            value_field: slug
            display_fields: [title]
            required: false
            hint: 'Optional, the posts associated with this collection.'
      - label: Featured Image
        name: featuredImage
        widget: image
        allow_multiple: false
        required: false
        hint: 'Optional, the image associated with this post.'

  - name: posts
    label: Post
    folder: content/posts
    format: frontmatter
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    summary: '{{title}}'
    editor:
      preview: true
    identifier_field: uuid
    fields:
      - {label: Slug Fields, name: slugFields, widget: hidden, default: [createdDate, title]}
      - {label: Unique ID, name: uuid, widget: uuid}
      - {label: Title, name: title, widget: string}
      - label: Blog Post
        name: isBlogPost
        widget: boolean
        default: true
        required: false
        hint: Blog posts show up in the 'Blog Post' tab and on the homepage. If something isn't a blog post we will also hide the created date.
      - label: Author
        name: author
        widget: relation
        collection: authors
        search_fields: [name]
        value_field: name
        display_fields: [name]
        required: false
        hint: 'Optional, the author associated with this post.'
      - label: Categories
        name: categories
        widget: list
        field:
          label: Category
          name: categories
          widget: relation
          collection: categories
          search_fields: [name]
          value_field: name
          display_fields: [name]
          required: false
      - label: Content
        name: body
        widget: markdown
        preview: true
      - label: Summary
        name: summary
        widget: text
        required: false
        hint: 'Optional, a short description of the post.'
      - label: Featured Image
        name: featuredImage
        widget: image
        allow_multiple: false
        required: false
        hint: 'Optional, the image associated with this post.'
      - label: Created Date
        name: createdDate
        widget: datetime
        date_format: YYYY-MM-DD
        time_format: false
        format: YYYY-MM-DD
        picker_utc: true
        hint: The date associated with this post.

  - name: categories
    label: Category
    folder: content/categories
    format: frontmatter
    create: true
    slug: '{{name}}-{{uuid}}'
    identifier_field: uuid
    summary: '{{name}}'
    editor:
      preview: false
    fields:
      - {label: Unique ID, name: uuid, widget: uuid}
      - {label: Category Name, name: name, widget: string}

  - name: authors
    label: Author
    folder: content/authors
    format: frontmatter
    create: true
    slug: '{{uuid}}-{{name}}'
    summary: '{{name}}'
    editor:
      preview: false
    fields:
      - {label: Unique ID, name: uuid, widget: uuid}
      - label: Author Name
        name: name
        widget: string
        required: false

local_backend: true
