backend:
  name: github
  branch: main
  repo: PatrickMcGrath29/thegoodland
  squash_merges: true
  use_graphql: true
  site_domain: https://thegoodland.vercel.app
  base_url: https://thegoodland.vercel.app
  auth_endpoint: /api/auth

site_url: https://thegoodland.vercel.app
display_url: https://thegoodland.vercel.app

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: collections
    label: Collections
    folder: content/collections
    format: frontmatter
    create: true
    slug: '{{name}}-{{author}}'
    summary: '{{name}}'
    editor:
      preview: false
    fields:
      - {label: Slug Fields, name: slugFields, widget: hidden, default: [name, author]}
      - {label: Collection Name, name: name, widget: string}
      - label: Author
        name: author
        widget: relation
        collection: authors
        search_fields: [name]
        value_field: name
        display_fields: [name]
        required: false
        hint: 'Optional, the author associated with this collection.'
      - label: Summary
        name: summary
        widget: text
        required: false
        hint: 'Optional, a short description of the collection.'
      - label: Posts
        name: posts
        widget: list
        fields:
          - label: Post
            name: post
            widget: relation
            collection: posts
            search_fields: [title]
            value_field: slug
            display_fields: [title]
            required: false
            hint: 'Optional, the posts associated with this collection.'
      - label: Featured Image
        name: featuredImage
        widget: image
        allow_multiple: false
        required: false
        hint: 'Optional, the image associated with this post.'

  - name: posts
    label: Post
    folder: content/posts
    format: frontmatter
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    summary: '{{title}}'
    editor:
      preview: true
    identifier_field: uuid
    fields:
      - {label: Slug Fields, name: slugFields, widget: hidden, default: [createdDate, title]}
      - {label: Unique ID, name: uuid, widget: uuid}
      - {label: Title, name: title, widget: string}
      - label: Blog Post
        name: isBlogPost
        widget: boolean
        default: true
        required: false
        hint: Blog posts show up in the 'Blog Post' tab and on the homepage. If something isn't a blog post we will also hide the created date.
      - label: Author
        name: author
        widget: relation
        collection: authors
        search_fields: [name]
        value_field: name
        display_fields: [name]
        required: false
        hint: 'Optional, the author associated with this post.'
      - label: Categories
        name: categories
        widget: list
        field:
          label: Category
          name: categories
          widget: relation
          collection: categories
          search_fields: [name]
          value_field: name
          display_fields: [name]
          required: false
      - label: Content
        name: body
        widget: markdown
        preview: true
      - label: Summary
        name: summary
        widget: text
        required: false
        hint: 'Optional, a short description of the post.'
      - label: Featured Image
        name: featuredImage
        widget: image
        allow_multiple: false
        required: false
        hint: 'Optional, the image associated with this post.'
      - label: Created Date
        name: createdDate
        widget: datetime
        date_format: YYYY-MM-DD
        time_format: false
        format: YYYY-MM-DD
        picker_utc: true
        hint: The date associated with this post.

  - name: categories
    label: Category
    folder: content/categories
    format: frontmatter
    create: true
    slug: '{{name}}-{{uuid}}'
    identifier_field: uuid
    summary: '{{name}}'
    editor:
      preview: false
    fields:
      - {label: Unique ID, name: uuid, widget: uuid}
      - {label: Category Name, name: name, widget: string}

  - name: authors
    label: Author
    folder: content/authors
    format: frontmatter
    create: true
    slug: '{{uuid}}-{{name}}'
    summary: '{{name}}'
    editor:
      preview: false
    fields:
      - {label: Unique ID, name: uuid, widget: uuid}
      - label: Author Name
        name: name
        widget: string
        required: false

  - label: Pages
    name: pages
    files:
      - label: About Page
        name: about
        file: content/pages/about.md
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}

  - name: quote
    label: Quote
    folder: content/quotes
    format: frontmatter
    create: true
    slug: '{{uuid}}'
    summary: '{{text}}'
    editor:
      preview: false
    identifier_field: uuid
    fields:
      - {label: Unique ID, name: uuid, widget: uuid}
      - {label: Text, name: text, widget: text}
      - label: Reference
        name: referenceId
        widget: relation
        collection: references
        search_fields: [referenceName, authorName]
        value_field: uuid
        display_fields: [referenceName, authorName]
        required: true
        hint: 'The reference associated with this quote (book, sermon). If the referene is not known, select "Anonymous"'

      - label: Categories
        name: categories
        widget: list
        field:
          label: Category
          name: categories
          widget: relation
          collection: categories
          search_fields: [name]
          value_field: name
          display_fields: [name]
          required: false

      - label: Quote Link
        name: link
        widget: string
        required: false
        hint: 'A link associated with this quote, for further reading. If there is a link associated with the resource for this quote then this will take precedence over it.'

      - label: Created Date
        name: createdDate
        widget: datetime
        date_format: YYYY-MM-DD
        time_format: HH:mm
        format: YYYY-MM-DDTHH:mm:ssZ
        picker_utc: true
        default: ''
        hint: The timestamp when this quote was added to the collection.

  - name: references
    label: Quote Reference
    folder: content/references
    format: frontmatter
    create: true
    slug: '{{uuid}}-{{referenceName}}-{{authorName}}'
    summary: '{{referenceName}} by {{authorName}}'
    editor:
      preview: false
    fields:
      - {label: Unique ID, name: uuid, widget: uuid}
      - label: Reference Name
        name: referenceName
        widget: string
        required: false

      - label: Author Name
        name: authorName
        widget: string
        required: false

      - label: Resource Link
        name: link
        widget: string
        required: false
        hint: A link associated with this resource for further reading.

local_backend: true
