backend:
  name: git-gateway
  branch: main
  repo: PatrickMcGrath29/thegoodland
  squash_merges: true
  use_graphql: true

site_url: https://thegoodland.io
display_url: https://thegoodland.io

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: posts
    label: Post
    folder: content/posts
    format: frontmatter
    create: true
    slug: '{{uuid}}-{{title}}'
    summary: '{{title}}'
    editor:
      preview: false
    identifier_field: uuid
    fields:
      - {label: Unique ID, name: uuid, widget: uuid}
      - {label: Title, name: title, widget: string}
      - label: Author
        name: referenceId
        widget: relation
        collection: authors
        search_fields: [authorName]
        value_field: uuid
        display_fields: [authorName]
        required: false
        hint: 'Optional, the author associated with this post.'
      - label: Categories
        name: categories
        widget: list
        field:
          label: Category
          name: categories
          widget: relation
          collection: categories
          search_fields: [name]
          value_field: name
          display_fields: [name]
          required: false
      - label: Content
        name: body
        widget: markdown
        preview: true
      - label: Summary
        name: summary
        widget: text
        required: false
        hint: 'Optional, a short description of the post.'
      - label: Featured Image
        name: featuredImage
        widget: image
        allow_multiple: false
        required: false
        hint: 'Optional, the image associated with this post.'
      - label: Created Date
        name: createdDate
        widget: datetime
        date_format: YYYY-MM-DD
        time_format: false
        format: YYYY-MM-DD
        picker_utc: true
        hint: 'Optional, the date associated with this post.'

  - name: categories
    label: Category
    folder: content/categories
    format: frontmatter
    create: true
    slug: '{{name}}-{{uuid}}'
    identifier_field: uuid
    summary: '{{name}}'
    editor:
      preview: false
    fields:
      - {label: Unique ID, name: uuid, widget: uuid}
      - {label: Category Name, name: name, widget: string}

  - name: authors
    label: Author
    folder: content/authors
    format: frontmatter
    create: true
    slug: '{{uuid}}-{{authorName}}'
    summary: '{{authorName}}'
    editor:
      preview: false
    fields:
      - {label: Unique ID, name: uuid, widget: uuid}

      - label: Author Name
        name: authorName
        widget: string
        required: false

local_backend: true
